name: on-commit

on:  # yamllint disable-line rule:truthy
  - push

jobs:
  test_boilerplate:
    container: cariad/ci:1.2.0
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: hadolint Dockerfile
      - run: ./test-boilerplate.sh

  test_image:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Set up caching
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: buildx-${{ github.ref }}
          restore-keys: buildx-

      - name: Discover metadata
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: cariad/hugo-ci

      - name: Build
        uses: docker/build-push-action@v2
        with:
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache,mode=max
          pull: true
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}

      - name: Test
        run: ./test-image.sh --image cariad/hugo-ci:${GITHUB_REF##*/}
