name: on-commit

on:  # yamllint disable-line rule:truthy
  - push

jobs:
  test_boilerplate:
    container: cariad/ci:1.2.0
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: hadolint Dockerfile
      - run: ./test-boilerplate.sh

  test_image:
    runs-on: ubuntu-20.04

    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000

    env:
      LOCAL_IMAGE_NAME: localhost:5000/cariad/hugo-ci:local

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Set up caching
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: buildx-${{ github.sha }}
          restore-keys: buildx-

      - name: Build
        uses: docker/build-push-action@v2
        with:
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache,mode=max
          pull: true
          tags: ${{env.LOCAL_IMAGE_NAME}}

      - name: Test
        run: ./test-image.sh --no-build
